# Macro file for the visualization setting in the initialization phase 

# Create an OpenGL view and draw geometry
/vis/open OGLI
/vis/drawVolume

# Draw smooth trajectories at end of event
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth

# Axes, eventID
/vis/scene/add/axes 18 0 0 10 cm
/vis/scene/add/eventID

# Visibility
/vis/geometry/set/visibility world 2 false
/vis/geometry/set/visibility plane 1 false
/vis/geometry/set/visibility pad 0 false

# /vis/filtering/trajectories/create/particleFilter
# /vis/filtering/trajectories/particleFilter-0/add gamma
# /vis/filtering/trajectories/particleFilter-0/invert true

# /vis/modeling/trajectories/create/drawByParticleID
# /vis/modeling/trajectories/drawByParticleID-0/set neutron blue
# /vis/modeling/trajectories/drawByParticleID-0/set anti_proton red

# Specify view angle and zoom
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 90 -90
/vis/viewer/zoom 1.5
# /vis/viewer/set/projection perspective 20 deg
/vis/viewer/centreOn calorimeter
