# Macro file for the visualization setting in the initialization phase 

# Create an OpenGL view and draw geometry
/vis/open OGLI
/vis/drawVolume

# Draw smooth trajectories at end of event
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth

# Specify view angle and zoom
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 70 30
/vis/viewer/zoom 1.5
# /vis/viewer/set/viewpointThetaPhi 90 0
# /vis/viewer/zoom 20
/vis/viewer/set/projection perspective 20 deg
/vis/viewer/centreOn CAAB_phys 0

# Axes, eventID
/vis/scene/add/axes 18 18 0 10 cm
/vis/scene/add/eventID

# Visible and color settings
/vis/geometry/set/visibility world_log 0 false
/vis/geometry/set/forceSolid CAAB_log
/vis/geometry/set/forceSolid G10C_log
/vis/geometry/set/lineWidth CAST_log 0 3

/vis/geometry/set/colour CAAB_log 0 0.59 0.29 0   1
/vis/geometry/set/colour G10C_log 0 0    0    0.5 1
/vis/geometry/set/colour CAST_log 0 0.66 0    0   1

# /vis/filtering/trajectories/create/particleFilter
# /vis/filtering/trajectories/particleFilter-0/add gamma
# /vis/filtering/trajectories/particleFilter-0/invert true

# /vis/modeling/trajectories/create/drawByParticleID
# /vis/modeling/trajectories/drawByParticleID-0/set neutron blue
# /vis/modeling/trajectories/drawByParticleID-0/set anti_proton red
